### ISSUE TITLE
Open to a native rust implementation?

### ISSUE THREAD

**Issue by dralley** [yamaura/rpmvercmp#1]
If someone wants to call into librpm.so, https://github.com/rpm-software-management/librpm.rs is the best place to interface with that.

I have a functional native Rust implementation of the version compare function though, and I would like to package it as a crate and publish to https://github.com/rpm-rs

Would you be interested in A) taking a Rust implementation of RPM version string comparison and publishing it under the `rpmvercmp` name and B) (only if you want to) moving it to the rpm-rs org?

**Comment by dralley** [comment]
@yamaura

**Comment by yamaura** [comment]
The motivation behind creating this crate was to easily compare implementation-dependent version strings using system libraries in multiple environments with a single binary in cmdline.
If this goal can be achieved, I have no particular preference.
If your crate has an implementation, how about adding an option for native comparison using rpm-rs crate to cmdline and re-export it in this crate?

**Comment by dralley** [comment]
If you definitely want to have a system library option then I'm not sure if it makes sense to do both, it should probably just be different crates.

However I would still suggest adding this functionality to the official librpm Rust bindings https://github.com/rpm-software-management/librpm.rs
